// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wjvrropiiyogmosleidk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqdnJyb3BpaXlvZ21vc2xlaWRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNzMxOTgsImV4cCI6MjA3Mjg0OTE5OH0.cXkdR61x2BNRbdlEkLIv8pe8hUxd8dsY-ZemvwYseRU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});